### ISSUE TITLE
Need to reset libpdinstance for libpd to unity every time I restart the project

### ISSUE THREAD

**Issue by frettini** [LibPdIntegration/LibPdIntegration#1] opened 2018-10-16 23:48 UTC
Hi, I found that every time I open my project, my communication from libpd to unity don't work anymore. I have to delete the libpdinstance component and put it again for it to work. 
I am missing something in the process of creating those communications?

**Comment by NiallMoody** [comment] 2019-04-11 14:08
Hi! Sorry, I only just realised I didn't have notifications turned on for Issues. Is this still an problem for you? I can't seem to replicate it myself.

Just so we're on the same page, for libpd → unity communication the process is:

1. In your c# script, Bind() to the send object in your patch.
2. Add a function to your script that will be called whenever that send object sends something.
3. In the Inspector, connect that function to the relevant **libpd -> Unity Events** Event.

Also, does the [LibPdIntegration Test project](https://github.com/LibPdIntegration/LibPdIntegrationTests) work for you? That one has tests for all the permutations of libpd → Unity communications.

**Comment by NiallMoody** [comment] 2019-05-23 08:53
Following up on this, as I've run into it myself now.

It turns out that the problem is down to libpd's callbacks for events sent from libpd to Unity. While libpd can run multiple patches as separate instances, those callbacks don't come from individual instances, but from (global) libpd itself. I didn't realise this when I wrote my wrapper.

The result is that with the wrapper as it stands, only one LibPdInstance will ever receive those callbacks, and depending on the order any LibPdInstances were created, it's very likely it will receive callbacks for an entirely different instance.

This should be fixable, but the fix will probably be a little fiddly. In the meantime, libpd → Unity communication will only work if you have just a single LibPdInstance in your Unity scene. Multiple LibPdInstances will break that communication.

**Comment by NiallMoody** [comment] 2019-05-23 11:15
This has been fixed with [v2.0.2](https://github.com/LibPdIntegration/LibPdIntegration/releases/tag/v2.0.2).

I might rework the wrapper in future as I'm not convinced this is the most efficient solution, but it maintains backwards compatibility, which is my immediate concern.

**Closed as completed by NiallMoody** 2019-05-23 11:15 UTC
